# Generated by Django 4.1.1 on 2022-09-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
