# Generated by Django 4.1.1 on 2022-09-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('url', models.URLField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
                'ordering': ['-date_completed'],
            },
        ),
    ]
