# Generated by Django 4.1.1 on 2022-09-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
