# Generated by Django 4.1.1 on 2022-09-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
        migrations.AlterModelOptions(
            name='framework',
            options={'ordering': ['level'], 'verbose_name_plural': 'Frameworks'},
        ),
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'ordering': ['level'], 'verbose_name_plural': 'Programming Languages'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name_plural': 'Tools'},
        ),
        migrations.AlterField(
            model_name='framework',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
    ]
