# Generated by Django 4.1.1 on 2022-09-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_framework_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='framework',
            options={'ordering': ['level'], 'verbose_name_plural': 'Frameworks'},
        ),
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'ordering': ['level'], 'verbose_name_plural': 'Programming Languages'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['title'], 'verbose_name_plural': 'Tools'},
        ),
    ]
