# Generated by Django 4.1.1 on 2022-09-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='institution_logo',
        ),
    ]
